spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/industrial_maintenance
    username: maintenance
    password: maintenance

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
